version: "3.5"

services:
    mongo:
        image: mongo:3.6
        networks:
            - mongo
        volumes:
            - mongo:/data/db
        deploy:
            replicas: 1
            restart_policy:
                condition: any

volumes:
    mongo:
        external: true

networks:
    mongo:
        driver: overlay
        ipam:
            config:
                - subnet: 172.47.0.0/16