version: "3.5"

services:
    ngsiproxy:
        image: fiware/ngsiproxy:1.1
        networks:
            - front
        environment:
            - TRUST_PROXY_HEADERS=1
        deploy:
            replicas: 1
            restart_policy:
                condition: any

networks:
    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16