version: "3.5"

services:
    perseo-core:
        image: telefonicaiot/perseo-core
        ports:
            - "8081:8080"
        depends_on:
            - orion
            - mongo
        environment:
            - MAX_AGE=630720000000
        command: -perseo_fe_url perseo-fe.docker:9090
        networks:
            perseo-core:
            front:
                aliases:
                    - perseo-core.docker
            mongo:
            orion:
        deploy:
            replicas: 1
            restart_policy:
                condition: any
    perseo-fe:
        image: telefonicaiot/perseo-fe
        ports:
            - "9090:9090"
        depends_on:
            - perseo-core
        environment:
            - PERSEO_MONGO_ENDPOINT=mongo
            - PERSEO_CORE_URL=http://perseo-core.docker:8080
            - PERSEO_LOG_LEVEL=debug
            - PERSEO_ORION_URL=http://orion.docker:1026
            - PERSEO_SMTP_HOST=SMTP-SERVER
            - PERSEO_SMTP_PORT=587
            - PERSEO_SMTP_SECURE=true
            - PERSEO_SMTP_AUTH_USER=SMTP-USER
            - PERSEO_SMTP_AUTH_PASS=SMTP-PASS
        networks:
            perseo-fe:
            front:
                aliases:
                    - perseo-fe.docker
            mongo:
            orion:
        deploy:
            replicas: 1
            restart_policy:
                condition: any

networks:
    perseo-core:
        driver: overlay
        ipam:
            config:
                - subnet: 172.60.0.0/16
    perseo-fe:
        driver: overlay
        ipam:
            config:
                - subnet: 172.61.0.0/16
    front:
        driver: overlay
        ipam:
            config:
                - subnet: 172.40.0.0/16
    mongo:
        driver: overlay
        ipam:
            config:
                - subnet: 172.47.0.0/16
    orion:
        driver: overlay
        ipam:
            config:
                - subnet: 172.41.0.0/16